# -*- coding: utf-8 -*-
"""
Created on Sun Mar 15 14:17:12 2020

@author: marcg
"""

##How to count bases in a sequencie
#ASsign a dummy sequence for practice
sequence = str("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC")


#write a function to count
#using the built in .count() built-in function
def BaseCounter(sequence):
    A = sequence.count("A")
    C = sequence.count("C")
    G = sequence.count("G")
    T = sequence.count("T")
    print (A,C,G,T,sep = ' ')


#run the function on the test sequence    
BaseCounter(sequence)
    
#Now download the test sequence from Rosalind and run the function
RosaSequence = "CTCCTTCGAGCGAGGAAGTCAAAATCGAGTGCACTGGTGGAAATAATATTCATACTGGACGGCGAAATCAATTATAACAGAACTGGGACCGGTGGGATCTCGCTTGGGCCATTTGTGTCAGGCGTTTATGCATGAAATACAGATCGCATGCTCAGTTAAATTGGGCTTAGCCGGATCCGCTCTACAGGTCTATCCGATGTTTTGCGTCATGGTTTGATTTGTATGCTAGTAGAATGGGCGCGCAGTGGGTCTGGGTCCTACCCAGCATACCAGCGTTACCCGTCGAGCCTACTAATAGGATAATTGACTACATCCATGCATGCTGAAAAAAGGAGCTCTACATCAGGATTTAGCTATCACCTGTTCGCCGACCAATTAATTGGAAACTGTCCTAGAGTTCACCACCCGCCGTTGTAACAATAAGTAGAGCACTGAGGTCGAAGGAGTTAAAACTGAACCTTCTCCTCTACGACACTTTTACCAATAAATTTCCGCACACAGTAAGCGTCCTGCTTGACACGTCTAGATGAGGGGGCTACCCTTCCCGGTAACCTATGGATAATCGCTGTTGCGCCCAGCACCCGCGAACCATTACTCCGCACCATAACTACTGTCGCATAACCGACCGGCGTACCACTATGCTGGGGCCTTTTTTCTGAAGGCAAAATGCCCAGAAAAGACGGCAGGGTCAGCACCACGTGTGCTGCTATACGACGGACATCGTTGTTGGGGCCTAGCCTAGACCTGGGGAATTACAATATCCTAAGGACATTCTTCAGTAGCTCCAGAGGAAGGTCGAGGTGAATCTTCTATACATCGGAAATTTGAATACCGTCAATTGCCGTTGCAAGGTAGAAAGAATACGGAAGCGTCGTCTGCCATCCGTATTAATACACGCGGGTAGACGTGCGTCCACTCCTGCG"
BaseCounter(RosaSequence)