# -*- coding: utf-8 -*-
"""
Created on Sun Mar 15 14:17:12 2020

@author: marcg
"""

# Goal is to generate the reverse complement of a sequence
#Must bear in mind that as well as changing bases, the\
#sequence is also reversed

#Generate a function to do this work
def reverseComplement(sequence):
    complements = {'A':'T', 'C':'G', 'T':'A', 'G':'C'} #What bases are going to be switched to
    revseq = reversed(sequence) #Reverse the input
    compseq = [complements[b] for b in revseq] #Change the reversed sequence to its complement
    return ''.join(compseq)

#Unit test the function with the example
input1 = "AAAACCCGGT"
reverseComplement(input1)

RosaRevC = "TATTTATCATCATCTATAATCTGACTATCCGAGCTGTGCCACGGGGTGTCGACGTCGTTTTGAGCGTGTGCATTTACTTTTCTCTTCTTTACTAGTCCGATGGAATCATACATATATCGGCCAGACACAAGCGGCGGGAAGCGGATTGTGTGGTTTGATCTTACTACGCCCATCTCACTGACGCGGATACAGGTTACGCTCGCAGTTCTCTGTTGTCTCCTGACGTCCGTGGCTGTGGCTGGACGCTTTATGGTATCACCCTGCGAATCCCTTGCATAGTAGCGTTACGAATCGCATTATGATGGCTCGCATGCCACCACGTCATATTAGTGGAAAGACTGCGTAGCATAGTCGTGAGCCACAACCTGAGAATGCATTTCCAAGCGCCGATCAGGACCTGTTAAATAGCTTACTGTATGTTCCACATGTACTGGACAAAAAGGCTGGATTAGGCTCTCCATAAGCCCCGGCGTCGACCAGTAGATCTCGCGGAGTTCTAGTGCGTCGGGCCTATCTGCGAAAGTGGAGAGAGTTGTATCGACATGTCTTCCCCGACCGCAACTTAAATACAACAGGCCCCTGAAGAGTCCTTCCCCCCTTAACACGCCACAAATCACTACTTCTTAACTGTTCGGCTGACTAAAGATGAACTAGAAATCTCGTTAGTAAACCGTCTGAACATTTCTCGAAAATGGCCCGTTCTCGTTGACGATAGTTGGTTATGCCAGAGCAGCTGAACATTGCTCTCTGTTCTAGCTGATCGAGCTGGTGGCATGAGTATTATTTATAGCGGTACCAGCGTAGATAACAGCCCGTTGTCGGACCTATCTTCAGGTTGAACCTCAGCTACCAACGTTATGAGTGCGTCCTGAGTGCGGTTCCGCCGTTGCCGAGTTACTGCCCATCACGGCTGTGTTTCAAAATTGAGTCCGTAGGTAATAAGTATGTGGA"
reverseComplement(RosaRevC)