# -*- coding: utf-8 -*-
"""
Created on Sat May 30 18:09:30 2020

@author: marcg

Import and install a module from BioPython
Write a function to count the bases in a DNA strint
"""
from Bio.Seq import Seq

#This is the example on Rosalind 'Intro to the bioinformatics armory

def CountBases(x):
    my_seq = Seq(x)
    A=my_seq.count("A")
    T=my_seq.count("T")
    G=my_seq.count("G")
    C=my_seq.count("C")
    print(A, C, G, T)


x = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'
CountBases(x)

#Below is the test problem

y = 'GTGCTTTATTTCGGGAGTTTATCCCTAAGACTATGTGTCGAACTGTAGATACGACGAGGCGCAGGAAGGAGTAGTATCGACCTGTCATCGCCCATAGCGTCGGCGAGCTACTAACCGAAGTGTATGTTAAGGTACGACAGGCGATTATTGGGTAGCCAAACGGGCTACTTCTAATAGCTAGAGAAATGCTGCTTGTCGCGAGATAGAGCAGTTACCACTAGTACTGAGTCGGCTCTTATCAGGGAGGTCTACCTCATGTGACTGCCTCGGCGCATTGATGGCGTATCGTGGAATGACGGGCCCAATCTGAGAATCGCGCATAACGTCATCATCTTTTAGAACTTGGACCCAAAGGGGAAATCATCGACATTGGCAGACTTGGAAGGTGAAGGCTATGACCTCCCCAAGGAGCTAGTGCCTCTGGGAGCGGGAGACTAGGTGCTTCTGTCAAGTAACTCATCCGGGGGATCACAATCTAATTGGCCTACCGAGCTTTTCGTGGGCATTCGTATTGCGGTATAATCTGCAGCTAAGGAGACTCTCTAGTAGAGCTTGACGATAGCCGCTTCAACGGTATGGTAGAGACCTAGATGTTGACAACGCCATGAACGGGCCGTCGAAGTCCGAGGAGACAGTTCTACGTGCCTAGTTAGCGACAGTTCATGTAACCTGGGTAACACGGGTCATGGCGCCTTCATATAACTGTCCACCCAGAGGGAGCGGCCCAGTGTTCTGCAACAATTTCCGTAATCTGGATGGATACCTCGTCTGCTGTATGATTGATAATTGTACTGGCGAGTCATGAACTTCTTTCGCAATGGATTTGCCATATGTTATGGGCTCCCAACATGCTATGGGGGCATCTCTGCAATGCACAAGGTGAGAAACTGGTTCCAGAATTATTGACGCTTTGTTACTGGGTCGTATGACTTGAACCAGGTAATCGTGCTCTTCGGTTTGGCTGTGACACCAAGCTCATATGG'
CountBases(y)

#This returned the correct answer of 240 219 269 255